### ISSUE TITLE
Executable 'prepare_metadata.py' does not exist.

### ISSUE THREAD

**Issue by tkuanlun350** [neptune-ml/open-solution-ship-detection#10]
Hi, thank you for open your solution.

I am trying to use neptune but I an unable to generate metadata.csv as instructed.
The file prepare_metadata.py seems to be missing ?

**Comment by jakubczakon** [comment]
Sorry for that @tkuanlun350 .

I was moving stuff around, and forgot to copy that file from the private repo.
I've just added it here, so it should work just fine.

**Comment by tkuanlun350** [comment]
Thanks for your help :)
