### ISSUE TITLE
enabling dev_mode

### ISSUE THREAD

**Issue by sovvo** [neptune-ml/open-solution-ship-detection#4]
Hi

Using python 3.5 (without neptune), the following works.
python main.py -- train --pipeline_name unet

However I wish to debug using dev_mode and can't seem to pass through the flag.
python main.py -- train --pipeline_name unet --dev_mode

Error: No value provided for parameter 'dev_mode'

I think the click option is_flag for dev_mode means we shouldn't need to pass any values, so I'm doing something wrong?

Thanks

**Comment by marketneutral** [comment]
I agree there is some funny behavior with `click`... I can't even get the basic `--help` to work either. 

`python main.py --help` gives

```
neptune: Executing in Offline Mode.
neptune: Error: No value provided for parameter 'help'
```

**Comment by jakubczakon** [comment]
We have dropped click in the newest releases so it shouldn't be a problem anymore.
